In [5]:
import cv2
import tensorflow as tf
import os
from tensorflow.keras.preprocessing import image
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import load_model

In [6]:
# def predict(image_path):
#     """Use VGG19 to label image"""
#     img = image.load_img(image_path, target_size=image_size)
#     x = image.img_to_array(img)
#     x = np.expand_dims(x, axis=0)
#     x = preprocess_input(x)
#     model = load_model('animlas10.h5')
#     predictions = model.predict(x)
#     return decode_predictions(predictions, top=3)

In [10]:
# create function to parse the image and predict
def prepare(filepath):
    IMG_SIZE = 100
    x = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    x = cv2.resize(x, (IMG_SIZE,IMG_SIZE))
    x = x.reshape(-1, IMG_SIZE, IMG_SIZE, 1)
    x = tf.cast(x, tf.float32)
    return x
    
    
def predict(filepath):    
    CATEGORIES = ['Dog','Cat']
    model = load_model("catsdogs.model")
    predictions = model.predict([prepare(filepath)])
    return CATEGORIES[int(predictions[0][0])]
    

In [11]:
# # read image and predict
filepath = os.path.join("testing_cat.jpg")
# a = tf.cast(prepare(filepath), tf.float32)

#print((a))
print(predict(filepath))

Cat


In [12]:
print((a))

tf.Tensor(
[[[[ 1.]
   [ 2.]
   [ 2.]
   ...
   [36.]
   [27.]
   [19.]]

  [[ 2.]
   [ 1.]
   [ 2.]
   ...
   [29.]
   [18.]
   [13.]]

  [[ 1.]
   [ 2.]
   [ 3.]
   ...
   [21.]
   [13.]
   [ 7.]]

  ...

  [[ 2.]
   [ 4.]
   [16.]
   ...
   [19.]
   [12.]
   [ 7.]]

  [[ 2.]
   [ 5.]
   [17.]
   ...
   [19.]
   [13.]
   [ 7.]]

  [[ 2.]
   [ 7.]
   [19.]
   ...
   [19.]
   [13.]
   [ 6.]]]], shape=(1, 100, 100, 1), dtype=float32)
